name: Build and Patch Custom Boot

on:
  workflow_dispatch:
    inputs:
      boot_url:
        description: 'boot url'
        required: true
        default: 'https://files.catbox.moe/x5l8po.img'

jobs:
  patch_boot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libelf-dev clang lld wget

      - name: Compile KPatch
        run: |
          make -C tools/kpatch

      - name: Download User Boot
        run: |
          wget -O boot.img "${{ github.event.inputs.boot_url }}"

      - name: Execute Patching
        run: |
          ./tools/kpatch/kpatch patch -b boot.img -o patched_boot.img

      - name: Upload Patched Image
        uses: actions/upload-artifact@v4
        with:
          name: Patched_Boot_Poco_X5_Pro
          path: patched_boot.img
          
